language: node_js
node_js: 
- "stable"
env:
  global:
    - NODE_ENV=test
before_install:
- npm install -g mocha
- npm install 
script: 
- npm test
- npm run report-coverage
branches:
- only
- develop
directories:
  - node_modules